--- #YAML:1.0
name:               POE-Component-PluginManager
version:            0.67
abstract:           Make your POE programs plugin capable, really easy!
author:
    - whoppix <elektronenvolt@quantentunnel.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Unload:  0.03
    POE:            0.9999
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
