--- #YAML:1.0
name:                POE-Component-PluginManager
version:             0.61
abstract:            Make your POE programs plugin capable, really easy!
license:             perl
author:              
    - whoppix <elektronenvolt@quantentunnel.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Unload:                 0.03
    POE:                           1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
